### ISSUE TITLE
ASA Stats Disclaimer Page, Proposed Update

### ISSUE THREAD

**Issue by SCN9A** [asastats/static-pages#10]
The following presents the different types of disclaimers and propose an update to [ASA Stats Disclaimer Page](https://www.asastats.com/disclaimer/).

First I explain the relevant disclaimers for ASA Stats, an introduction. Then I provide custom statements suitable for ASA Stats.

Source of information: [Disclaimer Examples ](https://termly.io/resources/articles/disclaimer-examples/)

### Introduction
**Warranty Disclaimer**
Warranty disclaimers explain that sellers and service providers are not bound by any implied promises about their products in the event of failures or defects.
* Warranty disclaimers prevent you from being bound by faults and defects

**No Responsibility Disclaimer**
No responsibility disclaimers explain to users that your business will not be held responsible for any damages they suffer as a result of using your products or services.
* No responsibility disclaimers limit your liability for damages

**Investment Disclaimer**
Investment disclaimers explain that while a business may provide financial advice, it is not responsible for the consequences of acting on that advice.
* Investment disclaimers state that you take no responsibility for how others act on your advice

**No Guarantee Disclaimer**
No guarantee disclaimers state that a business makes no promises regarding the outcome of using its product or service.
* No guarantee disclaimers explain the limits of your products or services

**Fair Use Disclaimer**
If your site or app uses content from other sources, you need to include a fair use disclaimer to prevent your business from being accused of copyright infringement.
* Fair use disclaimers help you avoid copyright infringement claims

### Warranty Disclaimer
The information provided by ASA Stats on https://www.asastats.com (the "Site"') is for general informational purposes only. All information on the Site is provided in good faith, however ASA Stats makes no representation or warranty of any kind, express or implied regarding the accuracy, adequacy, validity, reliability, availability or completeness of any information on the Site.

### No Responsibility Disclaimer
ASA Stats is not liable for any damages arising from the use of or inability to use this Site or any material contained in it, or from any action or decision taken as a result of using the Site.

This Site offers links to other sites thereby enabling you to leave this Site and go directly to the linked site. ASA Stats is not responsible for the content of any linked site or any link in a linked site. The links are provided to assist visitors to the Information presented on ASA Stats Site and the inclusion of a link does not imply that ASA Stats endorses or has approved the linked site.

### Investment Disclaimer
Nothing provided by ASA Stats constitutes an investment recommendation, nor should any data or Content published by ASA Stats be relied upon for any investment activities.

ASA Stats strongly recommends that you perform your own independent research and/or speak with a qualified investment professional before making any financial decisions.

### No Guarantee Disclaimer
ASA Stats maintains the Site to enhance public access to price information for every ASA on the Algorand blockchain.
This is a service that is continually under development. While we try to keep the information timely and accurate, we make no
guarantees. We will make an effort to correct errors brought to our attention. 

### Fair Use Notice
The Site may contain copyrighted material whose use has not been specifically authorized by the copyright owner.
ASA Stats is making this information available in our efforts to advance the understanding of ASA price information on the Algorand blockchain. ASA Stats believes that this constitutes a "fair use" of the copyrighted material as provided for in section 107 of the US Copyright Law. If your copyrighted material appears on the Site and you disagree with our assessment that it constitutes "fair use." contact us.

**Comment by ipaleka** [comment]
> The information provided by ASA Stats on [ ASA Stats website] (the "Site"') is for general informational purposes only.

Is the following a valid rendering for this?

"The information provided by ASA Stats on [https://www.asastats.com](https://www.asastats.com) (the Site) is for general informational purposes only."

**Comment by ipaleka** [comment]
> No Responsibility “no liability” Disclaimer

Should this actually be "No Responsibility Disclaimer"?

**Comment by ipaleka** [comment]
As we have introduced "the Site", my opinion is that we should stick to it in the rest of the page:

> to use this site
to use the Site

>  of using the site
of using the Site

> This site offers
The Site offers

> to leave this site
to leave the Site

> presented on ASA Stats site
presented on the Site

> ASA Stats maintains this web site
ASA Stats maintains the Site

> ASA Stats website may contain copyrighted material
The Site may contain copyrighted material

**Comment by ipaleka** [comment]
Also, may be a lame question :), but we start with the "Warranty Disclaimer" header on top of the page, right?

**Comment by SCN9A** [comment]
> Also, may be a lame question :), but we start with the "Warranty Disclaimer" header on top of the page, right?

Yes, as we have introduced "the Site" under Warranty Disclaimer.

@ipaleka all previous suggestions/corrections have been implemented in the new edited version. Thank you

**Comment by SCN9A** [comment]
> Also, may be a lame question :), but we start with the "Warranty Disclaimer" header on top of the page, right?

Yes, as we have introduced "the Site" under Warranty Disclaimer.

@ipaleka all previous suggestions/corrections have been implemented in the new edited version. Thank you

**Comment by ipaleka** [comment]
Deployed

**Comment by AlgoRhythMatic** [comment]
Note - this was rewarded in a prior cycle, but not moved to archived (so performing this update now).
