### ISSUE TITLE
ASA Stats FAQ Page, Proposed Update

### ISSUE THREAD

**Issue by SCN9A** [asastats/static-pages#2]
Please find below proposed update for ASA Stats FAQ Page. This is a modified version of the great work presented in [Community draft](https://docs.google.com/document/d/1hxf9bxzJnklJ5M6oBEdCQGRx5kN6d3SxA06AO8sMfCo/edit) on Google Docs.

Aiming to provide a concise summary. I have made the following modifications:

1. Changed the outline to include 4 main sections: **General**, **ASA Stats Token & Rewards**, **Service Users**, **ASA Project Owners**.
2. Added new questions.
3. Deleted questions that I found repetitive, not a FAQ. 
4. Updated information on **Staking rewards**, **LP Rewards incentive program**, **Recent organisational changes** and all relevant content. 
5. Rephrased some ideas, thinking tone in business writing, and looking for your feedback.

The following resources were accessed for updates:
- [Refinement of weekly ASASTATS LP rewards incentive program](https://www.reddit.com/r/asastats/comments/svm1qa/refinement_of_weekly_asastats_lp_rewards/)
- [ASA Stats organizational changes - part 1](https://www.reddit.com/r/asastats/comments/tzr1d0/asa_stats_organizational_changes_part_1/)
- [ASA Stats organizational changes - part 2](https://www.reddit.com/r/asastats/comments/u175ld/asa_stats_organizational_changes_part_2/)
- [ASA Stats organizational changes - part 3](https://www.reddit.com/r/asastats/comments/u2qa6v/asa_stats_organizational_changes_part_3/)
- [ASA Stats Website](https://www.asastats.com/tokenomics/)

### General 

**What is ASA Stats?**
ASA Stats aims to provide a robust source for the price information of every ASA. One of the primary goals and a measure of success for ASA Stats project is the establishment of Decentralized Autonomous Organization (DAO) that will take over after the initial phase of the project is successfully finished.

**How can I access project information?**
We believe in decentralization and transparency. Every word written for a transparent project's organizational purposes should be publicly available.

ASA Stats has only one official communication channel - the [ASA Stats Channel](https://github.com/asastats/channel). 

- Please refer to [White paper](https://www.asastats.com/whitepaper.pdf), GitHub [Roadmap document](https://github.com/asastats/docs/blob/main/roadmap.md) for more details.
- Every [ASA Stats discussion](https://github.com/asastats/docs/blob/main/code-of-conduct.md#asa-stats-discussions) besides [DAO discussions](https://github.com/asastats/dao-discussion/discussions) will take place in the ASA Stats Channel's [discussions](https://github.com/asastats/channel/discussions).

The ASA Stats [Discord server](https://discord.gg/Vjx7w7pAC7), [subreddit](https://www.reddit.com/r/asastats/), and [Twitter](https://twitter.com/asastatscom) are Community's channels. Welcome on board.

**Who owns ASA Stats project?**
- Right now Ivica Paleka (@Ipaleka on Discord, u/hopemeetme on Reddit) is the founder and project owner of ASA Stats. He is referred to as Team. Team is founded just to secure meaningful governance by developing the ASA Stats software. The same goes with the funds in the ASA Stats pools, they are borrowed by the Team until a decentralized voting platform is deployed on Algorand Mainnet.
- The actual owners of this project are 45 selected governors.

**When will ASA Stats transition into DAO?**
Before 31 December 2023, the DAO whitepaper will be published, respectively after every piece of the website's code is documented, tested, and open-sourced, the Team will create and sign a smart contract that will unconditionally transfer custody over ASA Stats pools' accounts to the DAO governors.

**How did ASA Stats choose DAO governors?**
The initial governors (and their vote count) were defined in the [Open Letter](https://github.com/asastats/dao-discussion/discussions/1). All further governors will be defined in discussions in our [Github repository](https://github.com/asastats/dao-discussion/discussions).

**Can I still become a governor?**
Yes, the new governors will be those members of the ASA Stats community who have contributed to the project the most. 

After the allocated seats from the Open Letter for the members of the Algorand community are filled, we will discuss additional seats for the Algorand community members.

**Has ASA Stats secured enough funding?**
Yes, ASA Stats project secured enough funds for the development and deployment of all the [roadmap's sections](https://github.com/asastats/docs/blob/main/roadmap.md). There are enough funds under Team's control to secure wages in order to reach the DAO phase not later than December 2023.

**What method will the DAO use to vote?**
This is yet to be defined. Ongoing discussions can be found in official Channel, [DAO discussions](https://github.com/asastats/dao-discussion/discussions). We are exploring opportunities to work in partnership with Scholtz, Choice coin, Vote Coin (and possibly others) to provide an MIT licensed [voting dApp](https://github.com/asastats/dao-discussion/discussions/1#discussioncomment-1801805). As we get closer to the formation of the DAO, the community will discuss this and make further decisions.

### ASA Stats Token & Rewards

**What are the ASA Stats project wallets?**
You can find all the ASA Stats project wallets on the [Tokenomics page](https://www.asastats.com/tokenomics/) of ASA Stats website. A monthly transparency report will be provided to track the various activities associated with these wallets.

**Was there a token presale(s)?**
Yes, The presale options expired on the 15th of December.  Everything concerning the token presale(s) was organized around the debate in our Discord [#presale-discussion](https://discord.com/channels/906917846754418770/913188307310088253) channel. Please refer to the Presale section of the [ASA Stats Whitepaper](https://www.asastats.com/whitepaper.pdf) for full details about the presale.

**Does the ASA Stats Token have Clawback and Freeze enabled?**
No. They were removed permanently on the 25th of November, 2021 

**Where can I purchase the ASA Stats Token?**
The ASA Stats Token is available on [Tinyman AMM](https://app.tinyman.org/#/swap?asset_in=0&asset_out=393537671), [Algodex](https://app.algodex.com/trade/393537671). Please refer to [How To Buy](https://www.reddit.com/r/asastats/comments/rdcx6s/how_to_buy_asa_stats_token_asastats_393537671/) and [Algodex trading guide](https://about.algodex.com/docs/algodex-trading-guide-mainnet/) for more information.

**Does the ASA Stats token have utility, or is it just an investment?**
Once our API (Application Programming Interface) is fully implemented, the ASA Stats token will be used to purchase various professional services from ASA Stats, enable user access to paid features, and be used for governance voting in the future DAO.

**Can I stake the ASA Stats token?**
Staking pools with [Yieldy](https://yieldly.medium.com/a-note-from-the-founder-2-a-hard-months-work-pays-off-8eb750331fb9) will launch in April 2022. Please Follow Yeildly announcements for more details. 

**Are there Rewards for Liquidity Providers?**
Yes. Please refer to [ASASTATS LP rewards incentive program](https://www.reddit.com/r/asastats/comments/svm1qa/refinement_of_weekly_asastats_lp_rewards/).

**When the ASA Stats community should expect LP rewards each week?**
The LP rewards distribution will typically be sent out a few days after the close of each cycle (00:00 UTC each Sunday), and will always occur before the following week's snapshot.

**Can I get a free airdrop?**
Approximately 30% of the ASA Stats Airdrop budget is still unused, however, it’s unlikely that any further airdrops will occur in the next 6 months.

However, if you are already eligible, you can still claim your airdrop if you satisfy any of the following criteria:
You must have been a member of the ASA Stats community before the Whitepaper's release (11/25/2021) to get Discord, Twitter, Reddit, and Decipher airdrops.

- Discord Airdrop:. If you have the OG role and have not yet received your airdrop, please post about in the [#airdrop-discussion](https://discord.com/channels/906917846754418770/913195994408177665) channel and an admin will contact you.
- [Twitter Airdrop](https://www.reddit.com/r/asastats/comments/r230sn/asa_stats_twitter_followers_qualified_for_the/)
- [Reddit Airdrop](https://www.reddit.com/r/asastats/comments/r4dtd0/a_list_of_reddit_airdrop_qualifiers_who_havent/)
- Decipher Airdrop: If you purchased a ticket to Decipher (Live or virtual event) before the 25th of November, head to [#decipher-airdrop](https://discord.com/channels/906917846754418770/914149762004049930) in our Discord and follow the instructions in the pinned message.

**Can I get ASA Stats tokens for helping out?**
Absolutely. There are many ways to get rewarded:
1. **Reporting bugs** / **Requesting features**: To get rewarded, the following criteria must be met:
 - An issue for every bug report and a feature request should be created in the [issues](https://github.com/asastats/channel/issues).
 - The first time the bug has been reported, or the feature requested. 
2. **Adding valuable suggestions to official [discussions](https://github.com/asastats/channel/discussions)**.

**How do you estimate community rewards?**
ASA Stats uses the ‘damo’ measurement when discussing rewards. One damo is equal to 1,000,000 ASA Stats tokens. The rewards system is evolving as our community matures, but the process of defining community members' rewards is as transparent as the rest of our processes.

### Service Users

**Will I need to pay or hold tokens to use the website or its other prospective features?**
All the functionality that you have access to now will remain free, at least until the DAO is formed. Once the DAO is formed, the governor’s votes will determine future requirements.

However, in the pre-DAO phase, there will be new features introduced. Some of them will be paid (or require token holding) to access. Possible examples include:
-SMS, email, or browser alerts for events that you choose
-Increased number of addresses in a bundle
-Increased rate of API calls based on your payment tier

**Where does ASA Stats retrieve its data from?**
We always aim to use a provider’s API/SDK whenever it is possible. We use the Tinyman SDK for retrieving data from Tinyman. We have researched and analyzed other providers‘ smart contracts and escrow accounts, and in some cases, like Algofi, we have used their subsequently published SDK to improve our custom solution.

All ASA icons in the UI come from the Tinyman [asa-icons](https://github.com/tinymanorg/asa-list) GitHub repository.

**How does ASA Stats calculate my portfolio balance?**
ASA Stats utilises up-to-date token pricing from each Tinyman pool, and display the price you would receive from the sale of your entire wallet’s balance of that ASA during a single transaction.  As such, we take price impact into account for you when we calculate your portfolio’s balance. As more AMMs and DEXs arrive on the Algorand mainnet, we will begin to combine and aggregate results to determine your token’s values. The current price will be retrieved from all the available AMMs and DEXes in a way that brings the maximum value for the user asset. This will be achieved by calculating current liquidities and/or volumes for that asset on all AMMs and DEXes, and by providing the optimal amounts that should be sold on each of the AMMs or DEXes to the users.

**Why does my token price under the Tinyman swap subsection differ from some other price information sources?**
Observations of pricing differences generally relate to wallet addresses that hold a significant amount of some token. ASA Stats shows the real price and value for a token - exactly the value you'd get if you try to sell the full amount with a slippage of 0.0% in the Tinyman app.

**Why are the totals calculated in ALGO?**
We believe that great UX requires consistency, and that using ALGO as the default portfolio unifier is the obvious choice. You may check a value in USD by hovering your mouse over the main header showing the total amount in ALGO. We also have a toggle to convert to USD if that’s your preference. We plan to support additional fiat choices in the future via variable user settings.

**What does Not Evaluated mean?** 
It means no price is defined anywhere for an ASA. e.g. No liquidity pool for the token currently exists.

**Do I have to type in my wallet every time? Can’t I just connect it?**
For now, yes. Or you can bookmark the URL. You can use our service to check not just your portfolio, but also the balances of other wallets you might be interested in.

**I have a feature request / found a bug, what should I do?**
Tell us, please. We are committed to providing the best portfolio tracker, and the best user experience.  The best way is to create an issue for every bug report and a feature request in the [issues](https://github.com/asastats/channel/issues). This official method can get you ASA Stats rewards. Please refer to Question "Can I get ASA Stats tokens for helping out?" for more details.

You can always let us know in the #bug-report channel on our [Discord](https://discord.gg/Vjx7w7pAC7), in our [subreddit](https://www.reddit.com/r/asastats/), or by pinging us on [Twitter](https://twitter.com/asastatscom).

### ASA Project Owners
**Why is my token icon not shown?**
Please add the token icon to the Tinyman [asa-icons](https://github.com/tinymanorg/asa-list) GitHub repository, and ASA Stats will add it as soon as possible.

**Can I advertise my token or service on your platform?**
Not right now. In the pre-DAO phase, there will be no ads and no user tracking on our website. Once the DAO takes over, that will be something for the governors to decide.

**Whom shall I contact for business proposal/opportunity?**
ASA Stats believe in decentralization and transparency. The project has only one official communication channel - the [ASA Stats Channel](https://github.com/asastats/channel). If you have a business proposal, a suggestion, or a partnership possibility, we would love to hear from you.

**Comment by ipaleka** [comment]
Great work, thank you!

I've updated the relevant [static-pages](https://github.com/asastats/static-pages/tree/main/faq) repository section. Please everybody, feel free to update the [related htlm](https://github.com/asastats/static-pages/blob/main/faq/faq.html).

**Comment by AlgoRhythMatic** [comment]
> Great work, thank you!
> 
> I've updated the relevant [static-pages](https://github.com/asastats/static-pages/tree/main/faq) repository section. Please everybody, feel free to update the [related html](https://github.com/asastats/static-pages/blob/main/faq/faq.html).

I agree, this is great work!  Just glancing over beginning, I see a few grammatical errors, so I will submit them via replies to see how well it works in this format.

**Comment by AlgoRhythMatic** [comment]
In the "What is ASA Stats?" section - a grammar correction: "_is establishing of_" should be updated to "_is the establishment of_".  The complete new sentence:

_One of the primary goals and a measure of success for ASA Stats project is the establishment of decentralized autonomous organization (DAO) that will take over after the initial phase of the project is successfully finished._

**Comment by AlgoRhythMatic** [comment]
In the "How can I access project information?" section - IMO the following sentence does not really add anything: "_ASA Stats thrives to establish the organizational principles which shouldn't change in the DAO phase_."

If people disagree and feel it is needed, it should at least change to be grammatically correct by removing the "the" before "organizational principles":

_ASA Stats thrives to establish organizational principles which shouldn't change in the DAO phase._

**Comment by SCN9A** [comment]
> In the "What is ASA Stats?" section - a grammar correction: "_is establishing of_" should be updated to "_is the establishment of_". The complete new sentence:
> 
> _One of the primary goals and a measure of success for ASA Stats project is the establishment of decentralized autonomous organization (DAO) that will take over after the initial phase of the project is successfully finished._



> In the "What is ASA Stats?" section - a grammar correction: "_is establishing of_" should be updated to "_is the establishment of_". The complete new sentence:
> 
> _One of the primary goals and a measure of success for ASA Stats project is the establishment of decentralized autonomous organization (DAO) that will take over after the initial phase of the project is successfully finished._

Thank you, this has been corrected as advised.

**Comment by SCN9A** [comment]
> In the "What is ASA Stats?" section - a grammar correction: "_is establishing of_" should be updated to "_is the establishment of_". The complete new sentence:
> 
> _One of the primary goals and a measure of success for ASA Stats project is the establishment of decentralized autonomous organization (DAO) that will take over after the initial phase of the project is successfully finished._



> In the "What is ASA Stats?" section - a grammar correction: "_is establishing of_" should be updated to "_is the establishment of_". The complete new sentence:
> 
> _One of the primary goals and a measure of success for ASA Stats project is the establishment of decentralized autonomous organization (DAO) that will take over after the initial phase of the project is successfully finished._

Thank you, this has been corrected as advised.

**Comment by AlgoRhythMatic** [comment]
Note - this was rewarded in a prior cycle, but not moved to archived (so performing this update now).
