### ISSUE TITLE
Handling multiple addresses

### ISSUE THREAD

**Issue by kerrilija** [asastats/static-pages#21]
ASA Stats address field can remember multiple addresses. But if I want to add the second address, I can't access "drop down suggestions" from within the app. Therefore, it would be better if we have something like a "+" or "add" button that creates another field which again give us access to the "drop down suggestions" field.

**Comment by ipaleka** [comment]
Dblclick covers that workflow, right?

The mobile app will have favorites/listings below so we'll mirror that afterward.

**Comment by ipaleka** [comment]
https://github.com/asastats/channel/discussions/220
